@startuml
class Artiest {
    + ArtiestenGroepId : int? <<get>> <<set>>
    + ArtiestenGroep : ArtiestenGroep? <<get>> <<set>>
    + Optredens : List<Optreden> <<get>> <<set>>
}
ApplicationUser <|-- Artiest
@enduml
